name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install postgres
      run: sudo apt-get install postgresql postgresql-client
    - name: Update path
      run: find /usr/lib/postgresql/ -type d -name "bin" >> $GITHUB_PATH
    - name: check path
      run: echo $PATH
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run unit tests
      run: cargo test --verbose --all-features
      env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres
