on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always
  DB_HOST: localhost
  DB_PORT: ${{ job.services.postgres.ports[5432] }}
  DB_USER: postgres
  DB_PASSWORD: root
  DB_NAME: postgres

jobs:
  lint_fmt:
    name: cargo fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formating
        run: cargo fmt -- --check

  lint_clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run clippy
        run: cargo clippy --all-features -- --deny warnings

  tests:
    name: Tests
    strategy:
      matrix:
        mode: ["debug", "release"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Install postgreSQL (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y libpq-dev postgresql-15
          sudo service postgresql start && sleep 3
          sudo -u postgres psql --command "ALTER USER postgres PASSWORD 'root';"

      - name: Run tests (debug)
        if: matrix.mode == 'debug'
        run: RUST_TEST_THREADS=1 cargo test --all-features

      - name: Run tests (release)
        if: matrix.mode == 'release'
        run: RUST_TEST_THREADS=1 cargo test --all-features --release

  fuzz:
    name: Fuzz
    strategy:
      matrix:
        target: ["copy", "exec", "query"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Install postgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev postgresql
          sudo service postgresql start && sleep 3
          sudo -u postgres psql --command "ALTER USER postgres PASSWORD 'root';"

      - name: Run unit tests
        run: cargo test --verbose --all-features
